source 'https://rubygems.org/'

gem 'activerecord'
gem 'capybara'
gem 'pg'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'shotgun'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'timecop'
