development:
  adapter: postgresql
  encoding: unicode
  database: messaging_development
  pool: 2
  username: Pauline
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: messaging_test
  pool: 2
  username: Pauline
  password: password
